[package]
name = "lib3"
version = "0.1.0"
edition = "2021"

[dependencies]
mockall = { workspace = true, optional = true }
reqwest = { workspace = true }
serde =  { workspace = true }

[features]
tests = ["dep:mockall"]
