[workspace.dependencies]
mockall = "0.12.1"
reqwest = { version = "0.12.7", features = ["blocking"] }
serde = { version = "1.0.204", features = ["serde_derive"] }
lib1 = { path = "./lib1" }

[workspace]
members = ["bin*", "lib*"]
resolver = "2"
