[package]
name = "los3"
version = "0.1.0"
edition = "2021"

[dependencies]
actix = "0.13.5"
mockall = "0.12.1"
serde = { version = "1.0.204", features = ["serde_derive"] }
serde_json = "1.0.120"
tokio = "1.38.1"
