[package]
name = "lib1"
version = "0.1.0"
edition = "2021"

[dependencies]
actix = { workspace = true }
mockall = { workspace = true }
reqwest = { workspace = true }
serde =  { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
